### ISSUE TITLE
Define pattern to ignore

### ISSUE THREAD

**Issue by cenouro** [seattlerb/flay#47]
Hi. Is there a way to define patterns to ignore? For example, some repositories have in their code things like

``` ruby
    def method_name
        fail 'not implemented'
    end
```

This causes CodeClimate to report a big mass for these abstract methods. Thanks.

**Comment by zenspider** [comment]
To answer your question: no, not yet. I'm open to a PR for such a thing.

Are those meant to be TODOs or meant to be a method interface on an abstract class? If the latter, I'd highly recommend raising `NotImplementedError` instead.

**Comment by cenouro** [comment]
From what I have seen in some open source repos, it is meant to be a method interface on an abstract class. The thing is that people are using [Rubocop](https://github.com/bbatsov/ruby-style-guide#fail-method) style to raise exceptions. Regardless, I totally agree with using `NotImplementedError` instead, at least for abstract interfaces, and I will also contact Rubocop's maintainers regarding this.

Anyway, this idea was taken from a python lib, and here is the [small reference](http://nedbatchelder.com/code/coverage/excluding.html) if you wanna see more. I think it is a good idea to allow people to define what are their repos false positives.

**Comment by zenspider** [comment]
Well, this is one (more) case where I completely disagree with rubocop's style guidelines.

Again, I'm open to a PR for this. I think doing it with plain text the way your python example does will completely fall over dead. I'm open to suggestion.

**Comment by cenouro** [comment]
I will try to play around with this repo code base. Meanwhile, why do you think plain text will fall over dead?

**Comment by zenspider** [comment]
Where is this?

**Comment by jdickey** [comment]
.flayignore does not seem to have any effect. Advice?

**Comment by jdickey** [comment]
In a similar vein, the README claims that PathExpander's support for `-path_to_subtract` is accessible from the command line. This appears to be incorrect; e.g., running `flay -path_to_subtract ./tmp/gemset/**/*.rb .` produces the help display. Help *is* needed, but it's not on that screen.

**Comment by zenspider** [comment]
@jdickey you need to be able to distinguish between option and non-option processing and you typically do that on unix programs with a `--` or by ordering them so that they're unambiguous.

```
flay -path_to_subtract ./tmp/gemset/**/*.rb . # doesn't work, not a path, not an option
flay ./tmp/gemset/**/*.rb . -path_to_subtract  # doesn't work, not a path, not an option
flay -- ./tmp/gemset/**/*.rb . -path_to_subtract  # works fine

```

 In the case of your example, it's made a bit tougher because your path isn't actually a path. If it were pointing to a real file, it wouldn't bring up the help:

```
% flay -v lib -lib/gauntlet_flay.rb 
Processing lib/flay.rb
Processing lib/flay_erb.rb
Processing lib/flay_task.rb
Processing lib/minitest/stackprof_plugin.rb
Total score (lower is better) = 72
...
```

The .flayignore works too and works much like a .gitignore file:

```
% echo lib/gauntlet_flay.rb > .flayignore 
% flay -v lib
Processing lib/flay.rb
Processing lib/flay_erb.rb
Processing lib/flay_task.rb
Processing lib/minitest/stackprof_plugin.rb
Total score (lower is better) = 72
...
```

**Comment by zenspider** [comment]
No response from the OP and this is ancient, so I'm closing.
