### ISSUE TITLE
Flay not detecting duplicate code

### ISSUE THREAD

**Issue by prophittcorey** [seattlerb/flay#49]
Hello, 

I have ran Flay against some code that is obviously duped such as the test case:

```ruby
    ##
    # I am a dog.
    class Dog
      def x
        return "Hello"
      end
    end
    ##
    # I
    # am
    # a
    # cat.
    class Cat
      def y
        return "Hello"
      end
    end
```

However, I can't seem to get flay to report the duplication. I only receive `Total score (lower is better) = 0`

**Comment by prophittcorey** [comment]
Looks like my mass was too high (default).

**Comment by zenspider** [comment]
I've been tempted to either remove mass filtering, or drop the number down such something "simple" (eg a method with a single call + a local var arg) will be reported. Thoughts?
