### ISSUE TITLE
Invoking Flay During Code-Review/Unit Tests

### ISSUE THREAD

**Issue by shalecraig** [seattlerb/flay#53]
This is a great tool!

I wanted to ask about building this more sustainably. I currently do this manually (with regexes :cry:) on Flay's output.
### Situation
- I want to run Flay before submitting a PR to see if I can fixup the code I'm changing. I'm trying to find instances where if it was copy/pasted in the past. I'd also want it to call me out for copy/pasting code.
- Because I'm working in a legacy codebase where some code has been duplicated, I only care about the files in the diff I'm making. Fixing everything would be exhausting.
- In bash, I use `FILES=$(git diff --name-only HEAD $(git merge-base HEAD origin/master) | grep '[.]rb')` to find a list of files that have changed.
- Then, I invoke `flay`, then search for complaints where one duplications exist in `FILES`.
### Request

I'd expect to run `flay` in some way like `flay --only-care-about=FILES lib/*.rb` to only report issues where the issues include `FILES`.

**Comment by hadinishad** [comment]
If you want to only run flay for files in diff, then try using pronto (and pronto-flay). pronto will run flay only the diffs. https://github.com/mmozuras/pronto-flay

**Comment by zenspider** [comment]
Look at the `FlayTask`. It allows you to set up a threshold score where a failure should be. You can then use something like `Hoe`'s `timebomb` method to calculate a linear degrading value over time to ensure that your project's flay score reaches zero over time.

**Comment by zenspider** [comment]
No response. Closing.
