### ISSUE TITLE
NameError: uninitialized constant FlayTask::Flay

### ISSUE THREAD

**Issue by ajacques** [seattlerb/flay#61]
Dangit GitHub for creating this issue before I had a chance to fill everything out.

I just updated to the latest version of Flay (2.7.0 -> 2.8.0) and now my Rake task is failing.

Rake version: 11.1.2.

My Rakefile looks like this:
```
[...]
if Rails.env.test? || Rails.env.development?
  require 'flay_task'
  [...]
  FlayTask.new
  [...]
  task default: [:test, :flay]
end
```

After this Gem version bump, this now fails due to the error:
```
rake aborted!
NameError: uninitialized constant FlayTask::Flay
/var/lib/gems/2.3.0/gems/flay-2.8.0/lib/flay_task.rb:47:in `block in define'
Tasks: TOP => flay
(See full trace by running task with --trace)
```

It appears to be related to the commit: https://github.com/seattlerb/flay/commit/4781d22de036dcb6976ff5c04d38569b9912faae#diff-3709294f47edd3f57c91adb09fa9953eL47

In this commit, the require 'flay' was removed causing Rakefiles that only depend on the flay_task to break, as mine did.

Is this expected behavior?

There is a workaround to just require 'flay' in my Rakefile, but this seems like it would break all existing consumers of Flay if they use it directly from their Rakefile, like I did.

**Comment by zenspider** [comment]
Not expected behavior. A bug. Fixing now. Thanks!
