### ISSUE TITLE
Collaboration with Codacy

### ISSUE THREAD

**Issue by machadoit** [seattlerb/flay#68]
Hi there, João Machado from [Codacy](https://www.codacy.com) here.

We have a Flay integration, so that everyone that uses our website can get Ruby duplication analysis. You can check it at https://github.com/codacy/codacy-duplication-flay

Would you guys be interested on mentioning us as a out-of-box solution to run Flay on your code? You can also add your repo at [Codacy](https://www.codacy.com) to check it out, we are free for open source projects.

**Comment by zenspider** [comment]
What would we be collaborating on?

**Comment by machadoit** [comment]
Hi @zenspider,

The idea would be just a mention of Codacy as a solution that has Flay integrated. Something like this RuboCop section at http://rubocop.readthedocs.io/en/latest/automated_code_review/

**Comment by zenspider** [comment]
I'm not comfortable doing this.

**Comment by machadoit** [comment]
Hi @zenspider, it is no problem at all! If you consider have such a section in the future, let me know.

On a related note, Rubocop didn't have a section for these tools, and by their suggestion, I created one mentioning other tools as well https://github.com/bbatsov/rubocop/commit/16a4d43ac2466f7bcb5236b3b31cfde0bda660bf that looks like http://rubocop.readthedocs.io/en/latest/automated_code_review/ in case you are interested in checking it out.

Thank you for your time.
