### ISSUE TITLE
[ASK] how the DuplicateCode works

### ISSUE THREAD

**Issue by jellythomas** [seattlerb/flay#77]
Hello guys, i've a question how the DuplicateCode works, i've this line of code thats read as DuplicateCode:

job_positions_controller.rb
job_position = JobPosition.new

job_levels_controller.rb
job_level = JobLevel.new

i dont really get on how the rubycritic scan the duplicatecode, can anyone give me a hint? tq in advance

**Comment by zenspider** [comment]
With flay defaults, above is too simple/small to bother to report, I can't speak for how rubycritic uses flay. 

What flay sees of the above code is something similar to:

```ruby
s(:block,
  s(:lasgn, :job_position, s(:call, s(:const, :JobPosition), :new)),
  s(:lasgn, :job_level,    s(:call, s(:const, :JobLevel),    :new)))
```

2 assignments, 2 calls... exactly the same structure. Flay doesn't care what the names of the variables or classes are, only that their structure is the same. When flay reports it, it explicitly says "similar" code, not "duplicate" (unless it is):

```
1) Similar code found in :defn (mass = 10)
  A: example.rb:1
  B: example.rb:5

A: def x
B: def y
A:   job_position = JobPosition.new
B:   job_level = JobLevel.new
   end
```
