### ISSUE TITLE
Flay does not recognize ruby 3.1's hash literal value omission

### ISSUE THREAD

**Issue by mizutani256** [seattlerb/flay#79]
[Since 3.1, you can now do things like this:](https://rubyreferences.github.io/rubychanges/3.1.html#values-in-hash-literals-and-keyword-arguments-can-be-omitted)

```ruby
x, y = 100, 200
# => [100, 200]
# In hash literal
h = {x:, y:}
# => {:x=>100, :y=>200}
```

Flay's output for the above code is:

```
  test.rb:4 :: parse error on value "," (tCOMMA)
  skipping test.rb
Total score (lower is better) = 0
```

That is, it skips the entire file, apparently.

**Comment by zenspider** [comment]
This should be fixed by updating ruby_parser. Let me know if you have any problems.

**Comment by zenspider** [comment]
no response. closing.

**Comment by mizutani256** [comment]
Sorry for the delay, we didn't have the time to stop to update the gems in our projects. Seems to me it should fix the issue, but if anything happens I'll be sure to let you know.

I really appreciate the attention and patience! =)
