### ISSUE TITLE
parse error on value ")" (tRPAREN) on Rails ERb files

### ISSUE THREAD

**Issue by hakanai** [seattlerb/flay#82]
Running flay (as part of metrics_fu), I get errors parsing ERb files some time around updating to Ruby 3.0.

    parse error on value ")" (tRPAREN)
    skipping app/views/things/_form.html.erb

It seems like a minor issue because it continues to run and finishes without an outright failure, but we have a lot of views so the log gets flooded heavily with these errors.

I have tried also including flay-actionpack in case that fixed the issue, but no, I still get the errors despite having that gem installed as well.

**Comment by zenspider** [comment]
any chance you can provide me with a file or fragment that can reproduce your issue?

**Comment by hakanai** [comment]
One example:

```erb
<% title('page title') %>

<%= form_for(@thing) do |f| %>
  <%= f.error_messages(class: 'error') %>

  (omitting further form stuff)
<% end %>
```

And the error/warning comes out on the line with the `form_for(@thing)`.

**Comment by zenspider** [comment]
Ah. That's not valid ERB. The `=` needs to be removed from your `form_for` block.

Generic example:

```
9989 % ruby -rerubi -e 'puts Erubi::Engine.new("<%= x.each do %>42<% end %>").src' | ruby -cw
-:1: syntax error, unexpected ')'
...ring.new; _buf << ( x.each do ).to_s; _buf << '42'.freeze; e...
-:1: syntax error, unexpected `end', expecting ')'
....to_s; _buf << '42'.freeze; end ;
-:2: syntax error, unexpected end-of-input
_buf.to_s
-: compile error (SyntaxError)
```
vs
```
9990 % ruby -rerubi -e 'puts Erubi::Engine.new("<% x.each do %>42<% end %>").src' | ruby -cw
Syntax OK
```

**Comment by hakanai** [comment]
Is this also invalid ERB? https://apidock.com/rails/ActionView/Helpers/FormHelper/form_for

**Comment by zenspider** [comment]
Yes:
```
% ruby -rerubi -e 'puts Erubi::Engine.new(File.read ARGV.shift).src' bug82.erb
```
```ruby
_buf = ::String.new; _buf << ( form_for :person do |f| ).to_s; _buf << '
'.freeze; _buf << '  First name: '.freeze; _buf << ( f.text_field :first_name ).to_s; _buf << '<br />
  Last name : '.freeze; _buf << ( f.text_field :last_name ).to_s; _buf << '<br />
  Biography : '.freeze; _buf << ( f.text_area :biography ).to_s; _buf << '<br />
  Admin?    : '.freeze; _buf << ( f.check_box :admin ).to_s; _buf << '<br />
  '.freeze; _buf << ( f.submit ).to_s; _buf << '
'.freeze; end 
 _buf << '
'.freeze;
_buf.to_s
```

looks like there's a special form for it: https://github.com/jeremyevans/erubi#capturing-

**Comment by hakanai** [comment]
Right, so I gather flay-actionpack exists specifically to use Rails' ERB parser instead of the Ruby one when processing ERB.
Only problem is, having flay-actionpack loaded doesn't necessarily work -

What happens on my machine is, flay loads flay-actionpack's plugin file first, then after it, loads its own one and replaces the `process_erb` method again. So whatever flay-actionpack does gets undone immediately after.

It seems like this happens in some arbitrary order. It might be based on LOAD_PATH but it doesn't match the order gems are specified in the Gemfile...

I think the only way I'm getting this to work is if there were some way to remove the default erb plugin.

**Comment by piacsek** [comment]
> I think the only way I'm getting this to work is if there were some way to remove the default erb plugin.

Although it's not documented on the README, you can use a `.flayignore` file to exclude ERB files:

```shellscript

$ cat .flayignore 
./**/*.erb # ERB parsing is currently broken -> https://github.com/seattlerb/flay/issues/82
```

**Comment by piacsek** [comment]
> I think the only way I'm getting this to work is if there were some way to remove the default erb plugin.

You can use a `.flayignore` file to exclude ERB files:

```shellscript
$ cat .flayignore
# ERB parsing is currently broken -> https://github.com/seattlerb/flay/issues/82
./**/*.erb
```

CC @hakanai

**Comment by zenspider** [comment]
This is fixed
