### ISSUE TITLE
Not flagging duplicate RSpec tests

### ISSUE THREAD

**Issue by rangerscience** [seattlerb/flay#83]
I've got some inherited code that's some deeply nested, absolutely gigantic RSpec suites. For Reasons(tm), part way through some work involving the files, I 1) needed to duplicate a bunch of tests, and 2) needed to scan a PR for duplicated code that made it where it shouldn't. Anyway! Seems like Flay isn't picking up on it.

Example:

```
                    it 'calls ServiceWidget.complete_thing' do
                      expect(
                        mock_service_widget
                      ).to receive(:complete_thing).and_call_original
                      request
                    end
                    
                    it 'calls ServiceWidget.complete_thing' do
                      expect(
                        mock_service_widget
                      ).to receive(:complete_thing).and_call_original
                      request
                    end
```

Flay isn't reporting this duplicate, although it _is_ reporting other duplicate code in this suite. It doesn't look like it's reporting this duplicated code as part of a larger block of duplicated code, either, which is very much A Thing(tm) in this file (alas).

It's very, very possible that the size (and other things) about these suites are breaking Flay, although it is successfully reporting other places with duplicate and similar code.

**Comment by zenspider** [comment]
```
% rake debug F=bug_rspec.rb M=5
Total score (lower is better) = 44

1) IDENTICAL code found in :iter (mass*2 = 44)
  bug_rspec.rb:2
  bug_rspec.rb:9
```

No response. Closing.
