### ISSUE TITLE
CLI return value

### ISSUE THREAD

**Issue by fauresebast** [seattlerb/flay#84]
I would like to have a non-zero exit code when using `bundle exec flay` to be able to use it in a CI and have a meaningful exit status.

I started to look at the code to see how can I contribute.

It is usually good to have a exit code giving more informations than 0 is OK, 1 is an error.

I saw 3 options here:
- Exiting with `self.total`
  - this is not possible because bash exit status has to be between 0-255
  - score is quickly above 255, leading to overflow, exit code is different from total score and we can have an exit code equal to 0 with a non-zero total score
 
- Exiting with `data.size` or `self.summary.size`
  - this is not possible because bash exit status has to be between 0-255, we could have more than 255 cases detected by the gem
   - both values are usually different, meaning a different exit code just by adding the summary option, it's losing its meaning
   
- Exiting with 0 if `self.total == 0`, 1 otherwise

I would like to have your thoughts about this before proposing a PR, maybe another interesting info to give as exit status ?

**Comment by zenspider** [comment]
I hesitated to do a non-zero exit code mainly so it does NOT get used in CI like that. Namely, this isn't dogma... It is signal for a human to look at and determine next steps. Some code SHOULD be repeated / should not be refactored and for good reason.

I'm open to having my mind changed.

That said, take a look at flay_task.rb

**Comment by zenspider** [comment]
No response for months... closing
